version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - ./shared/postgres:/var/lib/postgresql/data
      - ../dumps:/dumps
    ports:
      - 5432:5432
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  qvuantaverse:
    build: .
    container_name: qv
    depends_on:
      - postgres
      - redis
    tty: true
    volumes: 
      - /home/pavel/projects/quantaverse/qvwebapp:/qvwebapp # change to your work dir.
      - ~/.ssh/:/home/app/.ssh/:ro
    working_dir: /qvwebapp
    ports:
      - "3000:3000"
      - "9991:9991"
      - "8080:8080"
