FROM node

WORKDIR /home

COPY package*.json ./

RUN npm install --verbose

RUN npm install --save-dev webpack --verbose



RUN npm install webpack-dev-server --save-dev --verbose

RUN npm i -D webpack-cli --verbose
